namespace OzViewer;

static class HudCppExporter
{
    public static string ExportHeader(HudDocument doc)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// Auto-generated by HUD Editor - edit in tools/OzViewer and re-export");
        sb.AppendLine("#pragma once");
        sb.AppendLine();
        sb.AppendLine("namespace HudLayout {");
        sb.AppendLine($"  constexpr int GAME_WIDTH = {doc.GameWidth};");
        sb.AppendLine($"  constexpr int GAME_HEIGHT = {doc.GameHeight};");
        sb.AppendLine();

        foreach (var el in doc.Elements)
        {
            var name = ToCppName(el);
            sb.AppendLine($"  constexpr float {name}_X = {el.X}f;");
            sb.AppendLine($"  constexpr float {name}_Y = {el.Y}f;");
            sb.AppendLine($"  constexpr float {name}_W = {el.Width}f;");
            sb.AppendLine($"  constexpr float {name}_H = {el.Height}f;");
            sb.AppendLine();
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string ToCppName(HudElement el)
    {
        var f = Path.GetFileNameWithoutExtension(el.FileName).ToUpperInvariant()
            .Replace("-", "_").Replace(".", "_").Replace(" ", "_");
        return f;
    }
}
